broker_endpoint='http://storage_broker:50051'
pg_distrib_dir='/usr/local/'
listen_pg_addr='0.0.0.0:6400'
listen_http_addr='0.0.0.0:9898'
remote_storage={ endpoint='<{ neon-r2-endpoint }>', bucket_name='<{ neon-r2-bucket }>', bucket_region='<{ neon-r2-region }>', prefix_in_bucket='/<{ neon-r2-prefix }>/pageserver' }
control_plane_api='http://0.0.0.0:6666' # No storage controller on this host; a junk address, per upstream's compose
control_plane_emergency_mode=true
